# copy and paste this file to a new one called `config.toml`, with the following values filled in
[discord]
token="your discord token"
app_id="your discord app id"

[youtube]
yt_dlp_path="path to yt-dlp"
audio_download_path="path to download audio files to"